// Code generated by protoc-gen-go.
// source: protos/gotrpc.proto
// DO NOT EDIT!

/*
Package gotrpc is a generated protocol buffer package.

It is generated from these files:
	protos/gotrpc.proto

It has these top-level messages:
	OtrResponse
	OtrRequest
*/
package gotrpc

import proto "github.com/golang/protobuf/proto"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal

// The otr Response message
type OtrResponse struct {
	Plain  string `protobuf:"bytes,1,opt,name=plain" json:"plain,omitempty"`
	ToSend string `protobuf:"bytes,2,opt,name=toSend" json:"toSend,omitempty"`
	Error  string `protobuf:"bytes,3,opt,name=error" json:"error,omitempty"`
}

func (m *OtrResponse) Reset()         { *m = OtrResponse{} }
func (m *OtrResponse) String() string { return proto.CompactTextString(m) }
func (*OtrResponse) ProtoMessage()    {}

// The otr Request message
type OtrRequest struct {
	Message string `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
}

func (m *OtrRequest) Reset()         { *m = OtrRequest{} }
func (m *OtrRequest) String() string { return proto.CompactTextString(m) }
func (*OtrRequest) ProtoMessage()    {}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// Client API for OTRService service

type OTRServiceClient interface {
	Receive(ctx context.Context, in *OtrRequest, opts ...grpc.CallOption) (*OtrResponse, error)
	Send(ctx context.Context, in *OtrRequest, opts ...grpc.CallOption) (*OtrResponse, error)
}

type oTRServiceClient struct {
	cc *grpc.ClientConn
}

func NewOTRServiceClient(cc *grpc.ClientConn) OTRServiceClient {
	return &oTRServiceClient{cc}
}

func (c *oTRServiceClient) Receive(ctx context.Context, in *OtrRequest, opts ...grpc.CallOption) (*OtrResponse, error) {
	out := new(OtrResponse)
	err := grpc.Invoke(ctx, "/gotrpc.OTRService/Receive", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oTRServiceClient) Send(ctx context.Context, in *OtrRequest, opts ...grpc.CallOption) (*OtrResponse, error) {
	out := new(OtrResponse)
	err := grpc.Invoke(ctx, "/gotrpc.OTRService/Send", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for OTRService service

type OTRServiceServer interface {
	Receive(context.Context, *OtrRequest) (*OtrResponse, error)
	Send(context.Context, *OtrRequest) (*OtrResponse, error)
}

func RegisterOTRServiceServer(s *grpc.Server, srv OTRServiceServer) {
	s.RegisterService(&_OTRService_serviceDesc, srv)
}

func _OTRService_Receive_Handler(srv interface{}, ctx context.Context, codec grpc.Codec, buf []byte) (interface{}, error) {
	in := new(OtrRequest)
	if err := codec.Unmarshal(buf, in); err != nil {
		return nil, err
	}
	out, err := srv.(OTRServiceServer).Receive(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _OTRService_Send_Handler(srv interface{}, ctx context.Context, codec grpc.Codec, buf []byte) (interface{}, error) {
	in := new(OtrRequest)
	if err := codec.Unmarshal(buf, in); err != nil {
		return nil, err
	}
	out, err := srv.(OTRServiceServer).Send(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

var _OTRService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "gotrpc.OTRService",
	HandlerType: (*OTRServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Receive",
			Handler:    _OTRService_Receive_Handler,
		},
		{
			MethodName: "Send",
			Handler:    _OTRService_Send_Handler,
		},
	},
	Streams: []grpc.StreamDesc{},
}
